/*
  # Seed Initial Research Papers for CII Automation

  Seeds the research_papers table with initial high-quality papers from tier-1 sources
  to demonstrate the research ingestion and synthesis workflow.
*/

INSERT INTO research_papers (
  title,
  authors,
  abstract,
  publication_date,
  doi,
  study_type,
  sample_size,
  conditions,
  interventions,
  clinical_relevance,
  operational_relevance,
  reimbursement_relevance,
  quality_score,
  ai_summary,
  ai_clinical_implications,
  ai_operational_implications,
  ingestion_status
) VALUES
  (
    'Early intervention in musculoskeletal disorders reduces time to return to work',
    ARRAY['Smith J', 'Johnson M', 'Williams R'],
    'A randomized controlled trial examining the efficacy of early physiotherapy intervention in work-related musculoskeletal disorders. 523 patients were randomized to either standard care or early intensive intervention. Primary outcome was days to return to work.',
    '2023-11-15'::date,
    '10.1234/example.2023.001',
    'rct',
    523,
    ARRAY['musculoskeletal', 'work-related'],
    ARRAY['early intervention', 'intensive physiotherapy'],
    9,
    9,
    8,
    92,
    'Early physiotherapy intervention reduced average return to work time by 18 days (95% CI: 14-22 days) compared to standard care in work-related MSK disorders.',
    'Early, intensive physiotherapy is effective for reducing disability and return-to-work timeline in work-related musculoskeletal conditions. Consider implementing as standard protocol.',
    'Adopting early intervention protocols could reduce average case duration by 18 days, improving clinic throughput and reducing claim processing delays.',
    'processed'
  ),
  (
    'Predictive outcomes in rehabilitation: A machine learning approach',
    ARRAY['Chen L', 'Patel S', 'Kumar A'],
    'Retrospective analysis of 1,247 rehabilitation cases using machine learning to predict return-to-work outcomes. Model achieved 87% accuracy in predicting favorable outcomes within 60 days.',
    '2023-10-20'::date,
    '10.1234/example.2023.002',
    'cohort',
    1247,
    ARRAY['rehabilitation', 'outcome prediction'],
    ARRAY['machine learning', 'predictive modeling'],
    8,
    9,
    9,
    88,
    'Machine learning model successfully predicted favorable rehabilitation outcomes with 87% accuracy, potentially enabling earlier intervention timing.',
    'Predictive models can identify high-risk cases early, enabling targeted intervention strategies and improving outcomes.',
    'Implementing predictive models enables staff to prioritize cases, reduce unnecessary appointments for favorable-trajectory patients, and allocate resources efficiently.',
    'processed'
  ),
  (
    'Telehealth rehabilitation: Clinical outcomes and patient satisfaction',
    ARRAY['Thompson D', 'Martinez C', 'Lee K'],
    'Prospective cohort study comparing in-person and telehealth rehabilitation outcomes. 156 patients participated, with primary outcomes measured at 12 weeks follow-up.',
    '2023-09-10'::date,
    '10.1234/example.2023.003',
    'cohort',
    156,
    ARRAY['rehabilitation', 'telehealth'],
    ARRAY['remote rehabilitation', 'virtual therapy'],
    8,
    9,
    7,
    85,
    'Telehealth rehabilitation showed comparable outcomes to in-person care with improved patient satisfaction scores (8.2 vs 7.1, p<0.05).',
    'Telehealth rehabilitation is effective for routine follow-ups and monitoring, maintaining clinical outcomes while improving patient experience.',
    'Telehealth reduces facility overhead, improves patient access, and can increase clinic capacity. Consider hybrid model for appropriate cases.',
    'processed'
  ),
  (
    'Functional capacity assessment predicts work outcomes in occupational rehabilitation',
    ARRAY['Olson B', 'Anderson M', 'Brown T'],
    'Prospective study of 384 workers undergoing occupational rehabilitation. Functional capacity evaluation results were compared against 6-month return to work outcomes.',
    '2023-08-25'::date,
    '10.1234/example.2023.004',
    'cohort',
    384,
    ARRAY['occupational health', 'rehabilitation'],
    ARRAY['functional capacity evaluation'],
    9,
    8,
    8,
    87,
    'Functional capacity assessment showed strong predictive validity for return-to-work outcomes (sensitivity 84%, specificity 79%).',
    'Functional capacity evaluation is a valuable prognostic tool for occupational rehabilitation planning and outcome prediction.',
    'Early functional capacity assessment can stratify cases by risk level, enabling targeted intervention intensity and predicting realistic return-to-work timelines.',
    'processed'
  ),
  (
    'Claims management efficiency through evidence-based protocols',
    ARRAY['Davidson E', 'Robinson P', 'Taylor S'],
    'Quality improvement study implementing evidence-based claims management protocols across 8 clinics. Primary outcome was claims processing time and acceptance rate.',
    '2023-07-30'::date,
    '10.1234/example.2023.005',
    'case_series',
    612,
    ARRAY['claims management', 'operations'],
    ARRAY['evidence-based protocols', 'standardized workflows'],
    7,
    9,
    9,
    82,
    'Implementation of evidence-based protocols reduced average claims processing time by 23% and improved acceptance rate by 7 percentage points.',
    'Standardized, evidence-based documentation and clinical decision-making improves claims outcomes and reduces administrative burden.',
    'Process standardization reduces administrative overhead by 23%, improves reimbursement rates by 7%, and enables consistent outcomes across clinics.',
    'processed'
  ),
  (
    'Patient satisfaction and outcomes in integrated care models',
    ARRAY['Garcia F', 'Wilson J', 'Clark H'],
    'Comparative effectiveness study of traditional vs integrated rehabilitation care models. 428 patients enrolled with 12-week follow-up assessment.',
    '2023-06-15'::date,
    '10.1234/example.2023.006',
    'cohort',
    428,
    ARRAY['rehabilitation', 'care coordination'],
    ARRAY['integrated care model'],
    8,
    8,
    7,
    84,
    'Integrated care model demonstrated superior outcomes on patient satisfaction and functional recovery compared to traditional sequential care.',
    'Multidisciplinary integrated care improves patient outcomes and satisfaction. Coordination between disciplines is essential for better results.',
    'Integrated care reduces duplication, improves coordination, and enhances patient experience. May require operational restructuring but yields better metrics.',
    'processed'
  ),
  (
    'Benchmarking clinical outcomes across rehabilitation networks',
    ARRAY['Moore R', 'White L', 'Harris D'],
    'Multi-center retrospective study comparing clinical outcomes across 12 rehabilitation clinics. Analysis of 2,156 cases over 24-month period.',
    '2023-05-20'::date,
    '10.1234/example.2023.007',
    'case_series',
    2156,
    ARRAY['benchmarking', 'quality measurement'],
    ARRAY['outcome standardization'],
    8,
    9,
    6,
    86,
    'Significant variation in outcomes across clinics identified, with best-performing clinics achieving 32% better return-to-work timeframes.',
    'Large variation in outcomes suggests opportunities for practice improvement. Study best-performing clinics for protocol optimization.',
    'Benchmarking analysis shows best clinics achieve 32% superior outcomes. Opportunity for practice standardization and performance improvement initiatives.',
    'processed'
  ),
  (
    'Preventing secondary complications in prolonged rehabilitation cases',
    ARRAY['Singh M', 'Gupta N', 'Verma A'],
    'Interventional study testing early screening protocols for secondary complications. 267 patients randomized to standard monitoring vs enhanced screening.',
    '2023-04-10'::date,
    '10.1234/example.2023.008',
    'rct',
    267,
    ARRAY['complication prevention', 'rehabilitation'],
    ARRAY['early screening', 'proactive monitoring'],
    9,
    8,
    8,
    89,
    'Enhanced early screening protocol reduced secondary complications by 31% and overall case duration by 12 days.',
    'Proactive early screening for secondary complications prevents downstream issues, reduces disability progression, and improves outcomes.',
    'Enhanced screening reduces case duration by 12 days and complications by 31%, directly improving operational efficiency and reducing overall costs.',
    'processed'
  );
